services:
  tg-bot:
    build: .
    ports:
      - 3001:3001
    volumes:
      ${HOME}/docker/volumes/tg-bot/:/app
  caddy:
    image: caddy
    ports:
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${HOME}/docker/volumes/caddy/data:/data
      - ${HOME}/docker/volumes/caddy/config:/config    
