services:
  tgbot:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - caddy
  caddy:
    image: caddy
    command: set -a && source .env && set +a
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - ${HOME}/docker/volumes/caddy/data:/data
      - ${HOME}/docker/volumes/caddy/config:/config
