services:
  tgbot:
    build: .
    pull_policy: build
    ports:
      - 3001:3001
    env_file: stack.env
    depends_on:
      - caddy
  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${HOME}/docker/volumes/caddy/data:/data
      - ${HOME}/docker/volumes/caddy/config:/config
