services:
  tgbot:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - caddy
  caddy:
    image: caddy
    command: export $( grep -vE "^(#.*|\s*)$" .env )
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
      - ${HOME}/docker/volumes/caddy/data:/data
      - ${HOME}/docker/volumes/caddy/config:/config
