services:
  tgbot:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - caddy
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HOME}/docker/volumes/caddy/data:/data
      - ${HOME}/docker/volumes/caddy/config:/config
