services:
  tgbot:
    build: .
    ports:
      - 3001:3001
    env_file: stack.env
    depends_on:
      - caddy
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${HOME}/docker/volumes/caddy/data:/data
      - ${HOME}/docker/volumes/caddy/config:/config
