services:
  tgbot:
    build: .
    pull_policy: build
    ports:
      - 3001:3001
    restart: always
    env_file: stack.env
    depends_on:
      - caddy
    volumes:
      - /root/docker/volumes/tg-bot-aromimir:/app/data
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    pull_policy: build
    restart: always
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    volumes:
      - /root/docker/volumes/caddy/data:/data
      - /root/docker/volumes/caddy/config:/config
